import type { Metadata } from "next";
import Header from "@/components/Home/header";
import Footer from "@/components/Home/footer";
import TopBar from "@/components/Home/topBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopBar />
      <Header />
      {children}
      <Footer />
    </>
  );
}
